name: Deploy Release

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Use Bun
              run: |
                  bun i
                  bun run build
                  cd dist
            - name: Deploy
              run: |
                  rm ${{ secrets.PATH }}/* -R
                  cd dist
                  cp * ${{ secrets.PATH }}/ -R
                  cd ${{ secrets.ADDITIONALPATH }}
                  cp * ${{ secrets.PATH }}/ -R
                  cd ${{ secrets.PATH }}
                  chmod 755 * -R
                  chown www-data:www-data * -R
