name: Deploy Beta

on:
    push:
        branches:
            - master
            - dev

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Use Bun
              run: |
                  bun i
                  bun run build
                  cd dist
            - name: Deploy
              run: |
                  rm ${{ secrets.PATHBETA }}/* -R
                  cd dist
                  cp * ${{ secrets.PATHBETA }}/ -R
                  cd ${{ secrets.PATHBETA }}
                  chmod 755 * -R
                  chown www-data:www-data * -R
