name: Deploy Beta

on:
    push:
        branches:
            - master
            - dev

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20
              run: |
                  npm i
                  npm run build
                  cd dist
            - name: Deploy
              run: |
                  rm ${{ secrets.PATHBETA }}/* -R
                  cd dist
                  cp * ${{ secrets.PATHBETA }}/ -R
                  cd ${{ secrets.PATHBETA }}
                  chmod 755 * -R
                  chown www-data:www-data * -R
